Possibly a Python error, that has to be checked out...
